//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int RowID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Country_Code { get; set; }
        public string City_Code { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Phone { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Bill_Address { get; set; }
        public string Ship_Address { get; set; }
        public string Customer_Posting_Code { get; set; }
        public string Customer_Group { get; set; }
        public string Payment_Terms_Code { get; set; }
        public string Tax_ID { get; set; }
        public Nullable<decimal> Credit_Limit { get; set; }
        public Nullable<int> Clocked { get; set; }
        public string Picture { get; set; }
        public string Purchaser_Code { get; set; }
        public string Primary_Customer_Code { get; set; }
        public string Contact_Code { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string User_Login { get; set; }
        public string Search_Name { get; set; }
        public string Payment_Method { get; set; }
        public string Currency_Code { get; set; }
        public string Shipment_Method { get; set; }
        public Nullable<int> Company_Size { get; set; }
        public string HR_Bussiness_Group { get; set; }
        public Nullable<System.DateTime> Date_Of_Issue { get; set; }
        public string Place_Of_Issue { get; set; }
        public Nullable<System.DateTime> Date_Of_Constitutive { get; set; }
        public string Website { get; set; }
        public string Industry_Code { get; set; }
        public string Lead_Source { get; set; }
        public string Lead_Status { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_Modified { get; set; }
        public string Description { get; set; }
        public string Approve_User { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Chance_Code { get; set; }
        public string County_Code { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
