//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMSMoluxHongKongEntities : DbContext
    {
        public BMSMoluxHongKongEntities()
            : base("name=BMSMoluxHongKongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Item_Category> Item_Category { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<Price_Level> Price_Level { get; set; }
        public virtual DbSet<Price_Level_Detail> Price_Level_Detail { get; set; }
        public virtual DbSet<Sales_Order_Detail> Sales_Order_Detail { get; set; }
        public virtual DbSet<Sales_Order_Master> Sales_Order_Master { get; set; }
        public virtual DbSet<web_Cart> web_Cart { get; set; }
        public virtual DbSet<web_Company> web_Company { get; set; }
        public virtual DbSet<web_ConfigWebsite> web_ConfigWebsite { get; set; }
        public virtual DbSet<web_Contact> web_Contact { get; set; }
        public virtual DbSet<web_Footer> web_Footer { get; set; }
        public virtual DbSet<web_ItemImage> web_ItemImage { get; set; }
        public virtual DbSet<web_ItemSizeColor> web_ItemSizeColor { get; set; }
        public virtual DbSet<web_ItemTechnical> web_ItemTechnical { get; set; }
        public virtual DbSet<web_News> web_News { get; set; }
        public virtual DbSet<web_NewsCategory> web_NewsCategory { get; set; }
        public virtual DbSet<web_Partner> web_Partner { get; set; }
        public virtual DbSet<web_PaymentMethod> web_PaymentMethod { get; set; }
        public virtual DbSet<web_SizeColor> web_SizeColor { get; set; }
        public virtual DbSet<web_Slider> web_Slider { get; set; }
        public virtual DbSet<web_SocialNetwork> web_SocialNetwork { get; set; }
        public virtual DbSet<web_Technical> web_Technical { get; set; }
    
        [DbFunction("BMSMoluxHongKongEntities", "fnSplit")]
        public virtual IQueryable<fnSplit_Result> fnSplit(string sInputList, string sDelimiter)
        {
            var sInputListParameter = sInputList != null ?
                new ObjectParameter("sInputList", sInputList) :
                new ObjectParameter("sInputList", typeof(string));
    
            var sDelimiterParameter = sDelimiter != null ?
                new ObjectParameter("sDelimiter", sDelimiter) :
                new ObjectParameter("sDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplit_Result>("[BMSMoluxHongKongEntities].[fnSplit](@sInputList, @sDelimiter)", sInputListParameter, sDelimiterParameter);
        }
    
        [DbFunction("BMSMoluxHongKongEntities", "SplitRange")]
        public virtual IQueryable<SplitRange_Result> SplitRange(string code, string text)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitRange_Result>("[BMSMoluxHongKongEntities].[SplitRange](@code, @text)", codeParameter, textParameter);
        }
    
        [DbFunction("BMSMoluxHongKongEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[BMSMoluxHongKongEntities].[SplitString](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<sp_LoadPostByMenuID_Result> sp_LoadPostByMenuID(Nullable<int> menuID, Nullable<int> cateID)
        {
            var menuIDParameter = menuID.HasValue ?
                new ObjectParameter("menuID", menuID) :
                new ObjectParameter("menuID", typeof(int));
    
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoadPostByMenuID_Result>("sp_LoadPostByMenuID", menuIDParameter, cateIDParameter);
        }
    
        public virtual ObjectResult<sp_LoadPostFromMenuID_Result> sp_LoadPostFromMenuID(Nullable<int> menuID, Nullable<int> cateID)
        {
            var menuIDParameter = menuID.HasValue ?
                new ObjectParameter("menuID", menuID) :
                new ObjectParameter("menuID", typeof(int));
    
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoadPostFromMenuID_Result>("sp_LoadPostFromMenuID", menuIDParameter, cateIDParameter);
        }
    
        public virtual ObjectResult<sp_MultiSearchItem_Result> sp_MultiSearchItem(string keyWork, Nullable<int> pageSize, Nullable<int> pageIndex, string sortCriteria)
        {
            var keyWorkParameter = keyWork != null ?
                new ObjectParameter("keyWork", keyWork) :
                new ObjectParameter("keyWork", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var sortCriteriaParameter = sortCriteria != null ?
                new ObjectParameter("sortCriteria", sortCriteria) :
                new ObjectParameter("sortCriteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MultiSearchItem_Result>("sp_MultiSearchItem", keyWorkParameter, pageSizeParameter, pageIndexParameter, sortCriteriaParameter);
        }
    
        public virtual int sp_Test2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Test2", idParameter);
        }
    
        public virtual ObjectResult<sp_testproc_Result> sp_testproc(Nullable<int> menuID, Nullable<int> cateID)
        {
            var menuIDParameter = menuID.HasValue ?
                new ObjectParameter("menuID", menuID) :
                new ObjectParameter("menuID", typeof(int));
    
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_testproc_Result>("sp_testproc", menuIDParameter, cateIDParameter);
        }
    
        public virtual ObjectResult<web_get15ProductOther_Result> web_get15ProductOther(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_get15ProductOther_Result>("web_get15ProductOther", idParameter);
        }
    
        public virtual ObjectResult<web_get15ProductSameCategory_Result> web_get15ProductSameCategory(Nullable<int> id, string cateCode)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_get15ProductSameCategory_Result>("web_get15ProductSameCategory", idParameter, cateCodeParameter);
        }
    
        public virtual ObjectResult<web_get15ProductSameManufacturer_Result> web_get15ProductSameManufacturer(Nullable<int> id, string manuCode)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var manuCodeParameter = manuCode != null ?
                new ObjectParameter("manuCode", manuCode) :
                new ObjectParameter("manuCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_get15ProductSameManufacturer_Result>("web_get15ProductSameManufacturer", idParameter, manuCodeParameter);
        }
    
        public virtual ObjectResult<web_getAllItemLevel2_Result> web_getAllItemLevel2(Nullable<int> cateID)
        {
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllItemLevel2_Result>("web_getAllItemLevel2", cateIDParameter);
        }
    
        public virtual ObjectResult<web_getAllItemLevel2Filter_Result> web_getAllItemLevel2Filter(Nullable<int> cateID, string manuCode, string sortCriteria)
        {
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            var manuCodeParameter = manuCode != null ?
                new ObjectParameter("manuCode", manuCode) :
                new ObjectParameter("manuCode", typeof(string));
    
            var sortCriteriaParameter = sortCriteria != null ?
                new ObjectParameter("sortCriteria", sortCriteria) :
                new ObjectParameter("sortCriteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllItemLevel2Filter_Result>("web_getAllItemLevel2Filter", cateIDParameter, manuCodeParameter, sortCriteriaParameter);
        }
    
        public virtual ObjectResult<web_getAllManufacturerList_Result> web_getAllManufacturerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllManufacturerList_Result>("web_getAllManufacturerList");
        }
    
        public virtual ObjectResult<web_getAllNewsByCate_Result> web_getAllNewsByCate(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllNewsByCate_Result>("web_getAllNewsByCate", idParameter);
        }
    
        public virtual ObjectResult<web_getAllPartner_Result> web_getAllPartner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllPartner_Result>("web_getAllPartner");
        }
    
        public virtual ObjectResult<web_getAllPaymentMethod_Result> web_getAllPaymentMethod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllPaymentMethod_Result>("web_getAllPaymentMethod");
        }
    
        public virtual ObjectResult<web_getAllSliders_Result> web_getAllSliders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getAllSliders_Result>("web_getAllSliders");
        }
    
        public virtual ObjectResult<web_getCategoryLevel3ByLevel2_Result> web_getCategoryLevel3ByLevel2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getCategoryLevel3ByLevel2_Result>("web_getCategoryLevel3ByLevel2", idParameter);
        }
    
        public virtual ObjectResult<web_getChildCategory_Result> web_getChildCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getChildCategory_Result>("web_getChildCategory", idParameter);
        }
    
        public virtual ObjectResult<web_getChildCateNews_Result> web_getChildCateNews(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getChildCateNews_Result>("web_getChildCateNews", idParameter);
        }
    
        public virtual ObjectResult<web_GetCompanyById_Result> web_GetCompanyById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_GetCompanyById_Result>("web_GetCompanyById", idParameter);
        }
    
        public virtual ObjectResult<web_getConfigWebsite_Result> web_getConfigWebsite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getConfigWebsite_Result>("web_getConfigWebsite");
        }
    
        public virtual ObjectResult<web_getFooterByType_Result> web_getFooterByType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getFooterByType_Result>("web_getFooterByType", idParameter);
        }
    
        public virtual ObjectResult<web_getHeaderMenu_Result> web_getHeaderMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getHeaderMenu_Result>("web_getHeaderMenu");
        }
    
        public virtual ObjectResult<web_getItemCategoryById_Result> web_getItemCategoryById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getItemCategoryById_Result>("web_getItemCategoryById", idParameter);
        }
    
        public virtual ObjectResult<web_getLevel3Category_Result> web_getLevel3Category(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getLevel3Category_Result>("web_getLevel3Category", idParameter);
        }
    
        public virtual ObjectResult<web_getMultiSearchItem_Result> web_getMultiSearchItem(string keyWork, Nullable<int> pageSize, Nullable<int> pageIndex, string sortCriteria)
        {
            var keyWorkParameter = keyWork != null ?
                new ObjectParameter("keyWork", keyWork) :
                new ObjectParameter("keyWork", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var sortCriteriaParameter = sortCriteria != null ?
                new ObjectParameter("sortCriteria", sortCriteria) :
                new ObjectParameter("sortCriteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getMultiSearchItem_Result>("web_getMultiSearchItem", keyWorkParameter, pageSizeParameter, pageIndexParameter, sortCriteriaParameter);
        }
    
        public virtual ObjectResult<web_getParentCategory_Result> web_getParentCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getParentCategory_Result>("web_getParentCategory");
        }
    
        public virtual ObjectResult<web_getProductAdminFilter_Result> web_getProductAdminFilter(string keyword, string cateCode, string manuCode)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            var manuCodeParameter = manuCode != null ?
                new ObjectParameter("manuCode", manuCode) :
                new ObjectParameter("manuCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getProductAdminFilter_Result>("web_getProductAdminFilter", keywordParameter, cateCodeParameter, manuCodeParameter);
        }
    
        public virtual ObjectResult<web_getProductByCategory_Result> web_getProductByCategory(string cateCode)
        {
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getProductByCategory_Result>("web_getProductByCategory", cateCodeParameter);
        }
    
        public virtual ObjectResult<web_getProductByCategoryFilter_Result> web_getProductByCategoryFilter(string cateCode, string manuCode, string sortCriteria)
        {
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            var manuCodeParameter = manuCode != null ?
                new ObjectParameter("manuCode", manuCode) :
                new ObjectParameter("manuCode", typeof(string));
    
            var sortCriteriaParameter = sortCriteria != null ?
                new ObjectParameter("sortCriteria", sortCriteria) :
                new ObjectParameter("sortCriteria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getProductByCategoryFilter_Result>("web_getProductByCategoryFilter", cateCodeParameter, manuCodeParameter, sortCriteriaParameter);
        }
    
        public virtual ObjectResult<web_getProductDifferenceCategory_Result> web_getProductDifferenceCategory(Nullable<int> id, Nullable<int> cate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cateParameter = cate.HasValue ?
                new ObjectParameter("cate", cate) :
                new ObjectParameter("cate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getProductDifferenceCategory_Result>("web_getProductDifferenceCategory", idParameter, cateParameter);
        }
    
        public virtual ObjectResult<web_getProductSameCategory_Result> web_getProductSameCategory(Nullable<int> id, Nullable<int> cate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cateParameter = cate.HasValue ?
                new ObjectParameter("cate", cate) :
                new ObjectParameter("cate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getProductSameCategory_Result>("web_getProductSameCategory", idParameter, cateParameter);
        }
    
        public virtual int web_getRecursiveItemCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("web_getRecursiveItemCategory", idParameter);
        }
    
        public virtual ObjectResult<web_getSameLevelCategory_Result> web_getSameLevelCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getSameLevelCategory_Result>("web_getSameLevelCategory", idParameter);
        }
    
        public virtual ObjectResult<web_getSliderByType_Result> web_getSliderByType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getSliderByType_Result>("web_getSliderByType", idParameter);
        }
    
        public virtual ObjectResult<web_getTop5Item_Result> web_getTop5Item(Nullable<int> cateID)
        {
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getTop5Item_Result>("web_getTop5Item", cateIDParameter);
        }
    
        public virtual ObjectResult<web_getTop5ItemLevel1_Result> web_getTop5ItemLevel1(Nullable<int> cateID)
        {
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getTop5ItemLevel1_Result>("web_getTop5ItemLevel1", cateIDParameter);
        }
    
        public virtual ObjectResult<web_getTop5ItemLevel2_Result> web_getTop5ItemLevel2(Nullable<int> cateID)
        {
            var cateIDParameter = cateID.HasValue ?
                new ObjectParameter("cateID", cateID) :
                new ObjectParameter("cateID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getTop5ItemLevel2_Result>("web_getTop5ItemLevel2", cateIDParameter);
        }
    
        public virtual ObjectResult<web_getTop5ItemLevel3_Result> web_getTop5ItemLevel3(string cateCode)
        {
            var cateCodeParameter = cateCode != null ?
                new ObjectParameter("cateCode", cateCode) :
                new ObjectParameter("cateCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_getTop5ItemLevel3_Result>("web_getTop5ItemLevel3", cateCodeParameter);
        }
    
        public virtual ObjectResult<web_PaymentMethodList_Result> web_PaymentMethodList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_PaymentMethodList_Result>("web_PaymentMethodList");
        }
    
        public virtual ObjectResult<web_SocialNetworkList_Result> web_SocialNetworkList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<web_SocialNetworkList_Result>("web_SocialNetworkList");
        }
    }
}
