//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Level_Detail
    {
        public int RowID { get; set; }
        public string Price_Level { get; set; }
        public string Item_Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Price_Type { get; set; }
        public Nullable<int> Document_Type { get; set; }
        public string Item_Code_2 { get; set; }
        public Nullable<int> Qty_2 { get; set; }
    }
}
