//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Level
    {
        public int RowID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> Source_Type { get; set; }
        public Nullable<int> Type { get; set; }
        public string Source_Code { get; set; }
        public string User_Login { get; set; }
        public string Approve_User { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
