//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order_Master
    {
        public int RowID { get; set; }
        public string Code { get; set; }
        public string Customer_Code { get; set; }
        public string Bill_Customer_Code { get; set; }
        public string Ship_Customer_Code { get; set; }
        public string Bill_Address { get; set; }
        public string Bill_Address_2 { get; set; }
        public string Bill_Phone { get; set; }
        public string Bill_Fax { get; set; }
        public string Bill_Email { get; set; }
        public string Ship_Address { get; set; }
        public string Ship_Address_2 { get; set; }
        public string Ship_Phone { get; set; }
        public string Ship_Fax { get; set; }
        public string Ship_Email { get; set; }
        public string Payment_Terms_Code { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Saler_Code { get; set; }
        public Nullable<System.DateTime> Ship_Date { get; set; }
        public string Shipment_Method_Code { get; set; }
        public Nullable<int> Status { get; set; }
        public string User_Login { get; set; }
        public string Approve_User { get; set; }
        public string Branch_Code { get; set; }
        public string Sale_Note { get; set; }
        public string Sale_Rep { get; set; }
        public Nullable<int> Document_Type { get; set; }
        public string Payment_Method_Code { get; set; }
        public string Currency_Code { get; set; }
        public Nullable<decimal> Currency_Factor { get; set; }
        public Nullable<int> Ship { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Ship_Term { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Your_Reference { get; set; }
        public string Sales_Order_Code { get; set; }
        public Nullable<int> Ship_Type { get; set; }
        public Nullable<int> CheckTop { get; set; }
        public Nullable<System.DateTime> L_C_Date { get; set; }
        public string Sales_Quote_Order_Code { get; set; }
        public string Location_Code { get; set; }
        public Nullable<int> IsBanLe { get; set; }
    }
}
