//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order_Detail
    {
        public int RowID { get; set; }
        public string Sales_Order_Code { get; set; }
        public string Sales_Quote_Order_Code { get; set; }
        public string Item_Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Qty_Back_Order { get; set; }
        public Nullable<decimal> Qty_Ordered { get; set; }
        public Nullable<decimal> Qty_To_Order { get; set; }
        public Nullable<decimal> Qty_Exported_Inventory { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency_Code { get; set; }
        public Nullable<decimal> Currency_Factor { get; set; }
        public Nullable<decimal> Rate__LCY_ { get; set; }
        public Nullable<decimal> Amount__LCY_ { get; set; }
        public string User_Login { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Clocked { get; set; }
        public string Unit_Of_Measure { get; set; }
        public Nullable<decimal> Qty__per_Unit_of_Measure { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<decimal> Qty_Returned { get; set; }
        public Nullable<decimal> Qty_Invoiced { get; set; }
        public Nullable<decimal> Qty_Customsed { get; set; }
        public string Prive_Level { get; set; }
        public Nullable<decimal> Tolerance { get; set; }
        public string Lot_Size { get; set; }
        public string Location_Code { get; set; }
        public Nullable<decimal> C__Discount { get; set; }
        public Nullable<decimal> Discounted_Cash { get; set; }
        public Nullable<decimal> Amount_After_Discounted { get; set; }
        public Nullable<decimal> Amount__LCY__After_Discounted { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual web_SizeColor web_SizeColor { get; set; }
        public virtual web_SizeColor web_SizeColor1 { get; set; }
    }
}
