//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOLUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_ConfigWebsite
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string PhonePurchase { get; set; }
        public string Hotline { get; set; }
        public string CustomerService { get; set; }
        public string Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string TitleFooter1 { get; set; }
        public string TitleFooter2 { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string GoogleMap1 { get; set; }
        public string GoogleMap2 { get; set; }
        public string EmbedGoogleMap1 { get; set; }
        public string EmbedGoogleMap2 { get; set; }
        public string LogoBCT { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public string LicenseProvince { get; set; }
        public string IconSale { get; set; }
        public string IconNew { get; set; }
    }
}
