//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM_TTVEntities : DbContext
    {
        public CRM_TTVEntities()
            : base("name=CRM_TTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<demoData> demoDatas { get; set; }
        public virtual DbSet<demoType> demoTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbAction> tbActions { get; set; }
        public virtual DbSet<tbAttendance> tbAttendances { get; set; }
        public virtual DbSet<tbBanking> tbBankings { get; set; }
        public virtual DbSet<tbBookRoom> tbBookRooms { get; set; }
        public virtual DbSet<tbCallInbound> tbCallInbounds { get; set; }
        public virtual DbSet<tbCallOutBound> tbCallOutBounds { get; set; }
        public virtual DbSet<tbCategory> tbCategories { get; set; }
        public virtual DbSet<tbCategoryType> tbCategoryTypes { get; set; }
        public virtual DbSet<tbClass> tbClasses { get; set; }
        public virtual DbSet<tbCompany> tbCompanies { get; set; }
        public virtual DbSet<tbCompanyContact> tbCompanyContacts { get; set; }
        public virtual DbSet<tbCompanyFileAttach> tbCompanyFileAttaches { get; set; }
        public virtual DbSet<tbEducation> tbEducations { get; set; }
        public virtual DbSet<tbError> tbErrors { get; set; }
        public virtual DbSet<tbFamilyRelationship> tbFamilyRelationships { get; set; }
        public virtual DbSet<tbFileAttach> tbFileAttaches { get; set; }
        public virtual DbSet<tbLever> tbLevers { get; set; }
        public virtual DbSet<tbMenuAndForm> tbMenuAndForms { get; set; }
        public virtual DbSet<tbPartner> tbPartners { get; set; }
        public virtual DbSet<tbQuestion> tbQuestions { get; set; }
        public virtual DbSet<tbQueue> tbQueues { get; set; }
        public virtual DbSet<tbRegion> tbRegions { get; set; }
        public virtual DbSet<tbRole> tbRoles { get; set; }
        public virtual DbSet<tbRoleType> tbRoleTypes { get; set; }
        public virtual DbSet<tbRoom> tbRooms { get; set; }
        public virtual DbSet<tbScience> tbSciences { get; set; }
        public virtual DbSet<tbServicePack> tbServicePacks { get; set; }
        public virtual DbSet<tbSpecialized> tbSpecializeds { get; set; }
        public virtual DbSet<tbStudent> tbStudents { get; set; }
        public virtual DbSet<tbStudentFileAttach> tbStudentFileAttaches { get; set; }
        public virtual DbSet<tbSubject> tbSubjects { get; set; }
        public virtual DbSet<tbTimeFrame> tbTimeFrames { get; set; }
        public virtual DbSet<tbTimeStudy> tbTimeStudies { get; set; }
        public virtual DbSet<tbTimeTable> tbTimeTables { get; set; }
        public virtual DbSet<tbTranscript> tbTranscripts { get; set; }
        public virtual DbSet<tbUserFileAttach> tbUserFileAttaches { get; set; }
        public virtual DbSet<tbUserHistory> tbUserHistories { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
