//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class demoData
    {
        public int id { get; set; }
        public int idDemoType { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public bool bit { get; set; }
    
        public virtual demoType demoType { get; set; }
    }
}
