//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCallInbound
    {
        public int idCallInbound { get; set; }
        public Nullable<int> idEducation { get; set; }
        public Nullable<int> idSpecialized { get; set; }
        public Nullable<int> idServicePack { get; set; }
        public Nullable<int> idCompany { get; set; }
        public Nullable<int> callType { get; set; }
        public Nullable<int> callChanel { get; set; }
        public Nullable<int> idGroupComplaint { get; set; }
        public Nullable<int> idSubjectComplaint { get; set; }
        public Nullable<int> idReasonComplaint { get; set; }
        public string note { get; set; }
        public string customerStatut { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string suggestOfCL { get; set; }
        public Nullable<int> callResults { get; set; }
        public bool isExtremeFeedback { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> createBy { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
        public virtual tbCategory tbCategory1 { get; set; }
        public virtual tbCategory tbCategory2 { get; set; }
        public virtual tbCompany tbCompany { get; set; }
        public virtual tbEducation tbEducation { get; set; }
        public virtual tbServicePack tbServicePack { get; set; }
        public virtual tbSpecialized tbSpecialized { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
