//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCallOutBound
    {
        public int idCallOutBound { get; set; }
        public Nullable<int> idQueue { get; set; }
        public Nullable<int> outBoundType { get; set; }
        public string callDetail { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> createBy { get; set; }
        public Nullable<int> callStatus { get; set; }
        public Nullable<int> callResultsOB { get; set; }
        public Nullable<int> recordResultsOB { get; set; }
        public string note { get; set; }
        public Nullable<int> OBstate { get; set; }
        public Nullable<int> callNotable { get; set; }
        public Nullable<int> Criteria1 { get; set; }
        public Nullable<int> Criteria2 { get; set; }
        public Nullable<int> Criteria3 { get; set; }
        public Nullable<int> Criteria4 { get; set; }
        public Nullable<int> Criteria5 { get; set; }
        public Nullable<int> Criteria6 { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
        public virtual tbCategory tbCategory1 { get; set; }
        public virtual tbCategory tbCategory2 { get; set; }
        public virtual tbCategory tbCategory3 { get; set; }
        public virtual tbCategory tbCategory4 { get; set; }
        public virtual tbCategory tbCategory5 { get; set; }
        public virtual tbCategory tbCategory6 { get; set; }
        public virtual tbCategory tbCategory7 { get; set; }
        public virtual tbCategory tbCategory8 { get; set; }
        public virtual tbCategory tbCategory9 { get; set; }
        public virtual tbCategory tbCategory10 { get; set; }
    }
}
