//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompanyFileAttach
    {
        public int idCompanyFileAttach { get; set; }
        public Nullable<int> idCompany { get; set; }
        public string fileName { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public Nullable<int> uploadByUser { get; set; }
        public string roleID { get; set; }
        public string fileRole { get; set; }
        public string note { get; set; }
    
        public virtual tbCompany tbCompany { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
