//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCompany()
        {
            this.tbCallInbounds = new HashSet<tbCallInbound>();
            this.tbClasses = new HashSet<tbClass>();
            this.tbCompany1 = new HashSet<tbCompany>();
            this.tbCompanyContacts = new HashSet<tbCompanyContact>();
            this.tbCompanyFileAttaches = new HashSet<tbCompanyFileAttach>();
            this.tbQueues = new HashSet<tbQueue>();
            this.tbRoles = new HashSet<tbRole>();
            this.tbRooms = new HashSet<tbRoom>();
            this.tbUsers = new HashSet<tbUser>();
        }
    
        public int idCompany { get; set; }
        public Nullable<int> parentID { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<int> idRegion { get; set; }
        public string name { get; set; }
        public string taxCode { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string banking { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCallInbound> tbCallInbounds { get; set; }
        public virtual tbCategory tbCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClass> tbClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompany> tbCompany1 { get; set; }
        public virtual tbCompany tbCompany2 { get; set; }
        public virtual tbRegion tbRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompanyContact> tbCompanyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompanyFileAttach> tbCompanyFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbQueue> tbQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRole> tbRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRoom> tbRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers { get; set; }
    }
}
