//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompanyContact
    {
        public int idCompanyContact { get; set; }
        public int idCompany { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string position { get; set; }
        public string note { get; set; }
    
        public virtual tbCompany tbCompany { get; set; }
    }
}
