//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMenuAndForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMenuAndForm()
        {
            this.tbMenuAndForm1 = new HashSet<tbMenuAndForm>();
        }
    
        public int menuID { get; set; }
        public Nullable<int> parentID { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public string redirect { get; set; }
        public Nullable<int> sort { get; set; }
        public string jsonData { get; set; }
        public bool del { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> idAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMenuAndForm> tbMenuAndForm1 { get; set; }
        public virtual tbMenuAndForm tbMenuAndForm2 { get; set; }
        public virtual tbAction tbAction { get; set; }
    }
}
