//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRole()
        {
            this.tbFileAttaches = new HashSet<tbFileAttach>();
            this.tbStudentFileAttaches = new HashSet<tbStudentFileAttach>();
            this.tbUserFileAttaches = new HashSet<tbUserFileAttach>();
            this.tbUsers = new HashSet<tbUser>();
            this.tbUsers1 = new HashSet<tbUser>();
            this.tbUsers2 = new HashSet<tbUser>();
            this.tbUsers3 = new HashSet<tbUser>();
        }
    
        public int roleID { get; set; }
        public Nullable<int> idCompany { get; set; }
        public int idRoleType { get; set; }
        public string name { get; set; }
        public string role { get; set; }
        public int sort { get; set; }
        public string note { get; set; }
    
        public virtual tbCompany tbCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFileAttach> tbFileAttaches { get; set; }
        public virtual tbRoleType tbRoleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStudentFileAttach> tbStudentFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserFileAttach> tbUserFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUsers3 { get; set; }
    }
}
