//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRoom()
        {
            this.tbBookRooms = new HashSet<tbBookRoom>();
        }
    
        public int idRoom { get; set; }
        public int idCompany { get; set; }
        public string name { get; set; }
        public string roomCode { get; set; }
        public string roomSize { get; set; }
        public Nullable<int> maxStudent { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBookRoom> tbBookRooms { get; set; }
        public virtual tbCompany tbCompany { get; set; }
    }
}
