//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbScience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbScience()
        {
            this.tbClasses = new HashSet<tbClass>();
        }
    
        public int idScience { get; set; }
        public Nullable<int> idEducation { get; set; }
        public Nullable<int> idSpecialized { get; set; }
        public int idServicePack { get; set; }
        public string name { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public Nullable<int> studyTime { get; set; }
        public Nullable<int> unitPrice { get; set; }
        public Nullable<int> minimumStudents { get; set; }
        public Nullable<int> totalCoaches { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> createBy { get; set; }
        public string listIdSubject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClass> tbClasses { get; set; }
        public virtual tbEducation tbEducation { get; set; }
        public virtual tbServicePack tbServicePack { get; set; }
        public virtual tbSpecialized tbSpecialized { get; set; }
    }
}
