//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServicePack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbServicePack()
        {
            this.tbCallInbounds = new HashSet<tbCallInbound>();
            this.tbClasses = new HashSet<tbClass>();
            this.tbSciences = new HashSet<tbScience>();
        }
    
        public int idServicePack { get; set; }
        public Nullable<int> idEducation { get; set; }
        public int idSpecialized { get; set; }
        public string listIdSubject { get; set; }
        public string name { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCallInbound> tbCallInbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClass> tbClasses { get; set; }
        public virtual tbEducation tbEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbScience> tbSciences { get; set; }
        public virtual tbSpecialized tbSpecialized { get; set; }
    }
}
