//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTranscript
    {
        public int idTranscripts { get; set; }
        public int idUser { get; set; }
        public int idClass { get; set; }
        public int idSubjects { get; set; }
        public Nullable<int> achievements { get; set; }
        public Nullable<int> Scores { get; set; }
        public string note { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
        public virtual tbClass tbClass { get; set; }
        public virtual tbSubject tbSubject { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
