//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbBookRooms = new HashSet<tbBookRoom>();
            this.tbCallInbounds = new HashSet<tbCallInbound>();
            this.tbClasses = new HashSet<tbClass>();
            this.tbClasses1 = new HashSet<tbClass>();
            this.tbCompanyFileAttaches = new HashSet<tbCompanyFileAttach>();
            this.tbFamilyRelationships = new HashSet<tbFamilyRelationship>();
            this.tbFileAttaches = new HashSet<tbFileAttach>();
            this.tbQueues = new HashSet<tbQueue>();
            this.tbStudents = new HashSet<tbStudent>();
            this.tbStudentFileAttaches = new HashSet<tbStudentFileAttach>();
            this.tbTranscripts = new HashSet<tbTranscript>();
            this.tbUser1 = new HashSet<tbUser>();
            this.tbUserFileAttaches = new HashSet<tbUserFileAttach>();
            this.tbUserFileAttaches1 = new HashSet<tbUserFileAttach>();
            this.tbUserHistories = new HashSet<tbUserHistory>();
            this.tbUserHistories1 = new HashSet<tbUserHistory>();
        }
    
        public int userID { get; set; }
        public Nullable<int> idParent { get; set; }
        public Nullable<int> idCompany { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public Nullable<int> idState { get; set; }
        public Nullable<int> idJob { get; set; }
        public Nullable<int> healthStatus { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string experience { get; set; }
        public string trainingPlaces { get; set; }
        public string InternalNumber { get; set; }
        public Nullable<int> citizenship { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> district { get; set; }
        public string passport { get; set; }
        public Nullable<System.DateTime> dateIssued { get; set; }
        public string locationIssued { get; set; }
        public string homeTown { get; set; }
        public string resident { get; set; }
        public string address { get; set; }
        public string aspiration { get; set; }
        public bool sex { get; set; }
        public bool married { get; set; }
        public bool yogaLearned { get; set; }
        public string email { get; set; }
        public string skype { get; set; }
        public string facebook { get; set; }
        public string state { get; set; }
        public string code { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<int> groupMemb { get; set; }
        public Nullable<System.DateTime> dateUnlock { get; set; }
        public Nullable<System.DateTime> dateLock { get; set; }
        public Nullable<int> lever { get; set; }
        public Nullable<double> bonusScore { get; set; }
        public Nullable<double> accumulativePoint { get; set; }
        public Nullable<int> salary { get; set; }
        public bool partTime { get; set; }
        public bool working { get; set; }
        public Nullable<System.DateTime> dateToWork { get; set; }
        public Nullable<System.DateTime> dateTrialEnds { get; set; }
        public string codeHDLD { get; set; }
        public Nullable<System.DateTime> IssuedDateHDLD { get; set; }
        public Nullable<System.DateTime> HDLDStartDate { get; set; }
        public Nullable<System.DateTime> HDLDEndDate { get; set; }
        public string codeBHXH { get; set; }
        public string taxCode { get; set; }
        public Nullable<System.DateTime> DateRegisterTaxCode { get; set; }
        public string locationRegisterTaxCode { get; set; }
        public string banking { get; set; }
        public Nullable<int> roleID { get; set; }
        public string userRole { get; set; }
        public string menuRole { get; set; }
        public string password { get; set; }
        public bool locked { get; set; }
        public string reason { get; set; }
        public string note { get; set; }
        public string idAuthorize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBookRoom> tbBookRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCallInbound> tbCallInbounds { get; set; }
        public virtual tbCategory tbCategory { get; set; }
        public virtual tbCategory tbCategory1 { get; set; }
        public virtual tbCategory tbCategory2 { get; set; }
        public virtual tbCategory tbCategory3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClass> tbClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbClass> tbClasses1 { get; set; }
        public virtual tbCompany tbCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompanyFileAttach> tbCompanyFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFamilyRelationship> tbFamilyRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFileAttach> tbFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbQueue> tbQueues { get; set; }
        public virtual tbRegion tbRegion { get; set; }
        public virtual tbRegion tbRegion1 { get; set; }
        public virtual tbRole tbRole { get; set; }
        public virtual tbRole tbRole1 { get; set; }
        public virtual tbRole tbRole2 { get; set; }
        public virtual tbRole tbRole3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStudent> tbStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStudentFileAttach> tbStudentFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTranscript> tbTranscripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser> tbUser1 { get; set; }
        public virtual tbUser tbUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserFileAttach> tbUserFileAttaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserFileAttach> tbUserFileAttaches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserHistory> tbUserHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserHistory> tbUserHistories1 { get; set; }
    }
}
