//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_TTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserHistory
    {
        public int idUserHistory { get; set; }
        public Nullable<int> idUser { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> byUser { get; set; }
    
        public virtual tbUser tbUser { get; set; }
        public virtual tbUser tbUser1 { get; set; }
    }
}
